services:
  cloudsql-proxy:
    image: gcr.io/cloudsql-docker/gce-proxy:1.33.0
    command: /cloud_sql_proxy -instances=osged-494803:asia-southeast1:free-trial-first-project=tcp:0.0.0.0:5432
    restart: always

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  api-gateway:
    build: ./api-gateway
    ports:
      - "5001:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:6743@cloudsql-proxy:5432/flexistock
      - INVENTORY_SERVICE_URL=http://inventory-service:8080
      - ORDER_SERVICE_URL=http://order-service:8080
      - TRACK_SERVICE_URL=http://track-service:8080
      - FORECAST_SERVICE_URL=http://forecast_service:8080
      - SEARCH_SERVICE_URL=http://search-service:8080
    depends_on:
      cloudsql-proxy:
        condition: service_healthy

  inventory-service:
    build: ./inventory-service
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:6743@cloudsql-proxy:5432/flexistock
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      cloudsql-proxy:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  order-service:
    build: ./order-service
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:6743@cloudsql-proxy:5432/flexistock
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - FORECAST_API_URL=http://forecast-python:8000/forecast
      - INVENTORY_SERVICE_URL=http://inventory-service:8080
      - Google_MAP_API=${GOOGLE_MAPS_API_KEY}
    depends_on:
      cloudsql-proxy:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  track-service:
    build: ./track-service
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:6743@cloudsql-proxy:5432/flexistock
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      cloudsql-proxy:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  forecast_service:
    build: ./forecast_service
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:6743@cloudsql-proxy:5432/flexistock
      - RABBITMQ_URL=amqp://rabbitmq:5672
    depends_on:
      cloudsql-proxy:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  notification-service:
    build: ./notification-service
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:6743@cloudsql-proxy:5432/flexistock
      - RABBITMQ_URL=amqp://rabbitmq:5672
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
    depends_on:
      cloudsql-proxy:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  search-service:
    build: ./search-service
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://postgres:6743@cloudsql-proxy:5432/flexistock
    depends_on:
      cloudsql-proxy:
        condition: service_healthy

  forecast-python:
    build: ./forecast_service/pyservice
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq

  
